### ISSUE TITLE
data storage & structures

### ISSUE THREAD

**Issue by Jonstep101010** [Jonstep101010/ft_transcendence#7]
how is data structured in the database/databases?
blocks #6 
blocks #3

**Comment by aceauses** [comment]
Hey sir @Jonstep101010 

I have worked latelly on this concept of a database. The database is missing some features but i assume is a good start as we can learn and add more things with time, At the moment i have added lets say essentials structures and tables for our database, Please check it and let me now what you think about it.

[Click me](https://dbdiagram.io/d/672a2ce1e9daa85aca655160)

**Comment by aceauses** [comment]
Also Im trying to approach a Single Database, such as it will get very nested having to switch and connect to different databases at early development stages, as well as if we dont intend to make the website a large scale one, A single database should be more than enough for it

**Comment by Jonstep101010** [comment]
Currently I have implemented basic models for Game, Player and Dashboard at 5c443a957b1846af7f1100254199c6427185e92d with minimal attributes. 

LMK what to add
